const String BOT_TOKEN = 'YOUR_TOKEN';

const String BOT_SERVER_LOCAL_HOST = "localhost";

const int BOT_SERVER_LOCAL_PORT = 60000;

const String BOT_SERVER_WEBHOOK_URL = "YOUR_SERVING_WEBSERVER_URL";


