name: telebot
description: Telegram Bot client for dart.
version: 1.0.2
homepage: https://github.com/Arxing/dart-telebot
author: Arxing <meiswind711108@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^3.0.8
  json_annotation: ^3.0.0
  dartpoet: ^1.0.6+3
  named_mode: ^1.0.2+1
  shelf: ^0.7.5
  useful_extension: ^1.0.0
  meta: ^1.1.8
  trident: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.6.7
  json_serializable: ^3.2.2
  html: ^0.14.0+3
  trident_generator: ^1.0.0
